### ISSUE TITLE
Support .NET 3.5

### ISSUE THREAD

**Issue by agallardol** [radioman/WebRtc.NET#35]
Dear,

Is there any possibility of compiling the project so it can be incorporated into .NET 3.5? We are working to implement it in Unity, unfortunately Unity still uses .NET 3.5 and the new versions are found in Beta and have stability problems.

Thank you very much!

**Comment by radioman** [comment]
http://blogs.microsoft.co.il/arik/2011/05/30/how-to-use-a-net-4-based-dll-from-net-2-based-application/

_'Well, simply add COM to the mixture.. The idea is that you can expose the required classes from your DLL (which uses .NET Framework X) as COM classes (using COM Interop), and then use those classes from your other DLL (which uses .NET Framework Y). Since you are crossing a COM interface, in-process SxS will kick in and work its magic.'_

**Comment by radioman** [comment]
the other way would be using child process for .net4 host, providing required functions using remoting/pipes/http/etc

**Comment by Terricide** [comment]
You could also link to something like https://github.com/kekekeks/MonoLib that might help

**Comment by radioman** [comment]
p.s. staging branch x86 runs even on .net2
