### ISSUE TITLE
Linking x64

### ISSUE THREAD

**Issue by BO45** [radioman/WebRtc.NET#7]
Could you provide build instructions for x64? I'm having trouble linking the libvpx to the existing C++/CLI project. I follow the "gn gen" instructions, but I'm getting a lot of unresolved symbols when linking to WebRtc.NET (sse, avx etc.)

**Comment by radioman** [comment]
current build it 32bit only, i can make the x64 build but whats the point...

**Comment by km147** [comment]
I find this issue rather interesting an decided to do some research.  David Vanian, in this article suggests the following:

Any applications that require CPU usage such as transcoding, display performance and media rendering, whether it be audio or visual, will certainly require (at this point) and benefit from using 64 bit versus 32 bit due to the CPU's ability to deal with the sheer amount of data being thrown at it. It's not so much a question of address space as it is the way the data is being dealt with. A 64 bit processor, given 64 bit code, is going to perform better, especially with mathematically difficult things like transcoding and VoIP data - in fact, any sort of 'math' applications should benefit by the usage of 64 bit CPUs and operating systems. Prove me wrong.

http://stackoverflow.com/questions/2378399/are-64-bit-programs-bigger-and-faster-than-32-bit-versions

**Comment by radioman** [comment]
sounds like fairytales.. it's not performance issue anyway

**Comment by rlongre** [comment]
How about situations where a project with an existing 64-bit codebase would like to use WebRtc.NET? The more people that are able to use your lib, the more contributions you'll get. I happen to be in this boat but currently can't take up getting a 64-bit build working.

**Comment by radioman** [comment]
ok, i'll hit the build for x64, easy enough

**Comment by radioman** [comment]
i've made x64 build, use extra ram and no performance benefits though:
![webrtc_x32_vs_x64](https://s12.postimg.org/jt4c5bbil/webrtc_x32_vs_x64.jpg)
